<center> <font face= "product sans" style= "font-size:150px"> Freaqs! </font> </center>

Yah! Freqs!

Here we will take a quick look at the frequencies - and their modes.

In [1]:
import pandas as pd
import numpy as np

# 

## → Checking different freq modes in date_range
This is not just limited to the date_rage - with this I can explore the types of freqs which can be used for multimple purposes later.

# 

**SKIPPING:**
- **'D'** - Day : **'B'** - BusinessDay
- **'M'** - Month : **'BM'** - BusinessMonth
- **'MS'** - BeginMonth : **'BMS'** : BeginBusinessMonth
- **'T'** / **'min'** - Minutely
- **'S'** - Secondly
- **'L'** / **'ms'** - Millisecondly
- **'U'** - Microsecondly

# 

### `W-<day>`
That day - weekly

In [2]:
pd.date_range('6/1/2021', freq= "W-MON", periods= 5)

DatetimeIndex(['2021-06-07', '2021-06-14', '2021-06-21', '2021-06-28',
               '2021-07-05'],
              dtype='datetime64[ns]', freq='W-MON')

There is no `M-<day>` or something like that... because that means MONDAY each end on month... which is quite not feasible.

# 

### `WOM-<1/2/3/4><day>`
I guess this is amazing! <br>
Gives the date by day on perticular 'th' week (1 / 2 / 3 / 4)

**Sentence:** <br>
\>>> I want each montday from the second week of each month.

**Solution:** <br>
\>>> `WOM-2MON`
___
WOM = Week Of Month

# 

<center> → While I am typing this: This is saturday and date is 12th June 2021 (12 / 6 / 2021) ← </center>

In [3]:
# Getting all saturdays from 2nd weeks in year of 2021
pd.date_range('1/1/2021', periods= 12, freq= "WOM-2SAT")

DatetimeIndex(['2021-01-09', '2021-02-13', '2021-03-13', '2021-04-10',
               '2021-05-08', '2021-06-12', '2021-07-10', '2021-08-14',
               '2021-09-11', '2021-10-09', '2021-11-13', '2021-12-11'],
              dtype='datetime64[ns]', freq='WOM-2SAT')

WORKS! <br>
*(I have kept 2SAT because here - 12th June falls in 2nd week)*<br> There is the same date on 5th index (making it 6th number for june)

**NOTE:** As `W-<day>` example, here is also not any other like `WOY or WOD` which well, doesn't make any sense.

# 

### Using a GAP between dates
*(works on both - W and WOM setting)*

In [4]:
# Simple, MONDAY from EACH WEEK
pd.date_range('1/1/2021', periods= 12, freq= 'W-MON')

DatetimeIndex(['2021-01-04', '2021-01-11', '2021-01-18', '2021-01-25',
               '2021-02-01', '2021-02-08', '2021-02-15', '2021-02-22',
               '2021-03-01', '2021-03-08', '2021-03-15', '2021-03-22'],
              dtype='datetime64[ns]', freq='W-MON')

In [5]:
# Gaps, MONDAY from EACH 2nd WEEK
pd.date_range('1/1/2021', periods= 12, freq= '2W-MON')

DatetimeIndex(['2021-01-04', '2021-01-18', '2021-02-01', '2021-02-15',
               '2021-03-01', '2021-03-15', '2021-03-29', '2021-04-12',
               '2021-04-26', '2021-05-10', '2021-05-24', '2021-06-07'],
              dtype='datetime64[ns]', freq='2W-MON')

↑ Here to note that, it will give every second monday from the simple one. You can check. 

# 

In [6]:
# Simple, SATURDAY from 2nd week from each month
pd.date_range('1/1/2021', periods= 12, freq= 'WOM-2SAT')

DatetimeIndex(['2021-01-09', '2021-02-13', '2021-03-13', '2021-04-10',
               '2021-05-08', '2021-06-12', '2021-07-10', '2021-08-14',
               '2021-09-11', '2021-10-09', '2021-11-13', '2021-12-11'],
              dtype='datetime64[ns]', freq='WOM-2SAT')

In [7]:
# Gaps, SATURDAY from 2nd week from each 3rd month
pd.date_range('1/1/2021', periods= 12, freq= '3WOM-2SAT')

DatetimeIndex(['2021-01-09', '2021-04-10', '2021-07-10', '2021-10-09',
               '2022-01-08', '2022-04-09', '2022-07-09', '2022-10-08',
               '2023-01-14', '2023-04-08', '2023-07-08', '2023-10-14'],
              dtype='datetime64[ns]', freq='3WOM-2SAT')

# 

###  `Q-<mon>` 
It gives the LAST date of the month QUARTERLY

In [8]:
pd.date_range('1/1/2021', periods= 5, freq= "Q-JAN")

DatetimeIndex(['2021-01-31', '2021-04-30', '2021-07-31', '2021-10-31',
               '2022-01-31'],
              dtype='datetime64[ns]', freq='Q-JAN')

↑ See the difference ↓

In [9]:
pd.date_range('15/2/2021', periods= 5, freq= "Q-JAN")

DatetimeIndex(['2021-04-30', '2021-07-31', '2021-10-31', '2022-01-31',
               '2022-04-30'],
              dtype='datetime64[ns]', freq='Q-JAN')

Here the START date is changed but the freq stays the same. So this makes sence - that the frequency sets the time from which it has to start taking care of QUARTER.

# 

If we cange the freq ... it will reflect as assumed ↓

In [10]:
pd.date_range('15/2/2021', periods= 5, freq= "Q-FEB")

DatetimeIndex(['2021-02-28', '2021-05-31', '2021-08-31', '2021-11-30',
               '2022-02-28'],
              dtype='datetime64[ns]', freq='Q-FEB')

# 

###  `BQ-<mon>`
Last date of each month quarterly but it should be BUSINESS day.

In [11]:
# Simple day
pd.date_range('1/1/2021', periods= 5, freq= "Q-JAN")

DatetimeIndex(['2021-01-31', '2021-04-30', '2021-07-31', '2021-10-31',
               '2022-01-31'],
              dtype='datetime64[ns]', freq='Q-JAN')

In [12]:
# Business Day
pd.date_range('1/1/2021', periods= 5, freq= "BQ-JAN")

DatetimeIndex(['2021-01-29', '2021-04-30', '2021-07-30', '2021-10-29',
               '2022-01-31'],
              dtype='datetime64[ns]', freq='BQ-JAN')

↑ Observe the change in some dates...

**NOTE** *(Please note)*: When we keep 'Q-JAN' it will product the quarters from JAN but that will be non applicable in the real world setting. As it starts with the 1st month and end at 10th month - **doesn't cover all months in the year**.

**To get realistic result** we need to write either `Q` or `Q-DEC`. Which will start from month 3rd month and till 12th month.

# 

### `QS-<mon>` and `BQS-<mon>`
Tired of having the last date of month? Get the first date of the month qarterly

In [13]:
# Nomal days
pd.date_range('1/1/2021', periods= 5, freq= "QS-JAN")

DatetimeIndex(['2021-01-01', '2021-04-01', '2021-07-01', '2021-10-01',
               '2022-01-01'],
              dtype='datetime64[ns]', freq='QS-JAN')

In [14]:
# Buisness days
pd.date_range('1/1/2021', periods= 5, freq= "BQS-JAN")

DatetimeIndex(['2021-01-01', '2021-04-01', '2021-07-01', '2021-10-01',
               '2022-01-03'],
              dtype='datetime64[ns]', freq='BQS-JAN')

# 

### The same trick
Applies here, get the **GAPED** quarters.

In [15]:
# Simple days 2 quarters (start month)
pd.date_range('1/1/2021', periods= 5, freq= "2QS-JAN")

DatetimeIndex(['2021-01-01', '2021-07-01', '2022-01-01', '2022-07-01',
               '2023-01-01'],
              dtype='datetime64[ns]', freq='2QS-JAN')

In [16]:
# Business days 2 quarters (end month)
pd.date_range('1/1/2021', periods= 5, freq= "2BQ-JAN")

DatetimeIndex(['2021-01-29', '2021-07-30', '2022-01-31', '2022-07-29',
               '2023-01-31'],
              dtype='datetime64[ns]', freq='2BQ-JAN')

# 

### `A-<mon>` : `BA-<mon>` and `AS-<mon>` : `BAS-<mon>`
Get the dates in each year setting. Depending on the ***start / end*** of the month and ***normal / business*** days

In [17]:
pd.date_range('1/1/2021', periods= 10, freq= "A-JAN")

DatetimeIndex(['2021-01-31', '2022-01-31', '2023-01-31', '2024-01-31',
               '2025-01-31', '2026-01-31', '2027-01-31', '2028-01-31',
               '2029-01-31', '2030-01-31'],
              dtype='datetime64[ns]', freq='A-JAN')

In [18]:
pd.date_range('1/1/2021', periods= 10, freq= "A-FEB")

DatetimeIndex(['2021-02-28', '2022-02-28', '2023-02-28', '2024-02-29',
               '2025-02-28', '2026-02-28', '2027-02-28', '2028-02-29',
               '2029-02-28', '2030-02-28'],
              dtype='datetime64[ns]', freq='A-FEB')

# 

## → Considering TIME in the dates 

In the examples above, we gave just the dates in the start, so it generated automatically just dates. And hid the time from them. Because the time is 0 there which is not reqired or usable.

And if still you want to check that...
```python
pd.date_range('1/1/2021', periods= 10, freq= "A-FEB")[0]
>>> Timestamp('2021-02-28 00:00:00', freq='A-FEB')
```

There is the time, but as it is not requested, it has dropped the idea of showing in the array.

# 

Now, let's assume that - you have the time in the data - and you start making the dates from it... 

In [19]:
pd.date_range(start= '25/4/2021 5:20:1', periods= 2)

DatetimeIndex(['2021-04-25 05:20:01', '2021-04-26 05:20:01'], dtype='datetime64[ns]', freq='D')

See? It has considered the TIME now. But we are weird person -  ***we will reset the time before generating dates***

### `normalize = True`
According to the docs:
    
    normalize: bool, default False
        Normalize start/end dates to midnight before generating date range.

In [20]:
pd.date_range(start= '25/4/2021 5:20:1', periods= 2, normalize= True)

DatetimeIndex(['2021-04-25', '2021-04-26'], dtype='datetime64[ns]', freq='D')

KHOOL!

# 

# <center> | EXTRA STUFF | </center> 

## → `.repeat()`
There is the repeat method found in almost all pandas objects. Which will repeat each element given times.

**Why mentioned here?**: It is because I found the *.repeat()* function with date_range() for the first time, and when I came here to add it, I found that the repeat is NOT ONLY with date_range but it is also for numpy array and Series and more. So, added here.

In [5]:
np.arange(0, 10).repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8, 9, 9, 9])

# 

## → `np.tile()` 

Similar function is `.tile()` which does repetation in the order. Not like `.repeat()`

**NOTE:** *.tile()* is available in NUMPY, it is not a method like *.repeat()*. It is a high level function. 

We needed it to make repeatation which we can do with Lists by...
```python 
# Possible with Lists
[1,2,3] * 3
>>> [1,2,3,1,2,3,1,2,3]

# but not with Numpy
array([1,2,3]) * 3
>>> array([1,6,9])
```

In [9]:
np.tile(pd.date_range('25/4/2021', periods= 2), 3)

array(['2021-04-25T00:00:00.000000000', '2021-04-26T00:00:00.000000000',
       '2021-04-25T00:00:00.000000000', '2021-04-26T00:00:00.000000000',
       '2021-04-25T00:00:00.000000000', '2021-04-26T00:00:00.000000000'],
      dtype='datetime64[ns]')

# 

# That's it!
I guess for the basics of time, we should end the notebook here. Next up we will take a look at how offsets work (they are freaking amazing)