# ufuncs

Mostly the ufuncs have some other methods which help use to do more stuff. But they are very less known and used. 

Let's see below to understand it better.

In [1]:
import numpy as np

In [10]:
arr = np.arange(1, 10)

In [11]:
# Normal use
np.add(arr, 5)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

## np.ufunc.reduce() 

In [12]:
# With reduce
np.add.reduce(arr)

45

In [13]:
np.multiply.reduce(arr)

362880

Read the error ↓

In [17]:
np.divmod.reduce(arr)

ValueError: reduce only supported for functions returning a single value

# 

### `np.ufunc.accumulate()` 

In [18]:
np.add.accumulate(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

It shows the steps it took between to reach the result returned by reduce.

In [19]:
np.multiply.accumulate(arr)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

# 

## Quickly make a table 

## `np.ufunc.outer()` 

Does a cartesian product between the arrays and the outer array will have the shape of sum of shaped of the input arrays

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.multiply.outer(arr, np.arange(5))

array([[ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16],
       [ 0,  5, 10, 15, 20],
       [ 0,  6, 12, 18, 24],
       [ 0,  7, 14, 21, 28],
       [ 0,  8, 16, 24, 32],
       [ 0,  9, 18, 27, 36]])

# 

### I wanna reduce but on some points. 

## `np.ufunc.reduceat()`

In [25]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.add.reduceat(arr, [2,5,8])

array([12, 21,  9], dtype=int32)

↑ is equivalent to:
```python
np.array([arr[2:5].sum(), arr[5:8].sum(), arr[8:].sum()])
```

In [29]:
np.array([arr[2:5].sum(), arr[5:8].sum(), arr[8:].sum()])

array([12, 21,  9])

Also in ndaray...

In [31]:
arr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.add.reduceat(arr.reshape((3,3)), [0,2], axis= 1)

array([[ 3,  3],
       [ 9,  6],
       [15,  9]], dtype=int32)

Equivalent to...

In [47]:
aa = arr.reshape((3,3))

In [57]:
np.c_[aa[:, 0:2].sum(1)[:, np.newaxis], aa[:, 2:].sum(1)[:, np.newaxis]]

array([[ 3,  3],
       [ 9,  6],
       [15,  9]])

I know it is weird.

# 

So there were:
* ufunc.reduce
* ufunc.reduceat
* ufunc.accumulate
* ufunc.outer

# 

# Making own ufuncs 

There are several ways of making ufuncs... but the most basic way is with Numpy C API.

* `numpy.frompyfunc`
* `numpy.vectorize`

Are the most basic and cool functions.

## `np.frompyfunc()`
*It accepts minimum 3 inputs, <br>1. Function, 2. Number of Inputs, 3. Number of Outputs.*

In [100]:
# Basic function that does some task
def func(x, y):
    return (x * y)

In [101]:
# Making OWN UFUNC
prod_and_add = np.frompyfunc(func, 2, 1)

In [102]:
prod_and_add(np.arange(10), np.arange(10))

array([0, 1, 4, 9, 16, 25, 36, 49, 64, 81], dtype=object)

REMEMBER. These are the UFUNCS. So each time, one element is passed in the function. So... 
```python
def func(x, y):
    return (x * y)[0]

# or

def func(x, y):
    return (x * y).sum()

```
Will result in error. Because the time when you subscript, it is an integer. 

# 

### The return object
from the `frompyfunc` always return the python array object. If you need to change... you can not in that. You need to use another function...

## `np.vectorize` 

In [103]:
prod_and_add = np.vectorize(func, otypes= [np.float32])

In [105]:
prod_and_add(np.arange(5), np.arange(5))

array([ 0.,  1.,  4.,  9., 16.], dtype=float32)

# 

But thses are very slow than the native numpy version.

# 

# Next up
We will talk about the structured arrays

# 