# Here you will smell
A sense of Pandas, it is where the pandas is born.

# 

Normal numpy array, as we have discussed are not capable of holding heterogeneous data types because of the way they are represented in the memory. 

But the `structured` arrays solves that problem. It allows us to defined **our own** data type for the array and again works amazingly fast.

> A structured array is an ndarray in which each element can be thought of as representing a struct in C. Hence got the "structured" name.

# 

In [3]:
import numpy as np

## Basic syntax

In [4]:
# Define YOUR data type for EACH ROW
dtype = [('Name', str), ('Age', np.int8)]

In [5]:
dtype

[('Name', str), ('Age', numpy.int8)]

###### 

In [6]:
# Just create an array! No special things needed!
np.array([("Aayush", 12), ("Sameer", 55), ("Shah", 5)])

array([['Aayush', '12'],
       ['Sameer', '55'],
       ['Shah', '5']], dtype='<U6')

Wait... it turned everything to string!

In [7]:
# This is real syntax                             right here    ↓
np.array([("Aayush", 12), ("Sameer", 55), ("Shah", 5)], dtype= dtype)

array([('', 12), ('', 55), ('',  5)],
      dtype=[('Name', '<U'), ('Age', 'i1')])

Wait again... just  `str` won't work... we need like...

In [8]:
# Define YOUR data type for EACH ROW
dtype = [('Name', '<U10'), ('Age', np.int8)]

In [9]:
dtype

[('Name', '<U10'), ('Age', numpy.int8)]

In [10]:
# This is real syntax                             right here    ↓
np.array([("Aayush", 12), ("Sameer", 55), ("Shah", 5)], dtype= dtype)

array([('Aayush', 12), ('Sameer', 55), ('Shah',  5)],
      dtype=[('Name', '<U10'), ('Age', 'i1')])

## Done Done. 

# 

### Accessing 

In [11]:
struc_arr = np.array([("Aayush", 12), ("Sameer", 55), ("Shah", 5)], dtype= dtype)
struc_arr

array([('Aayush', 12), ('Sameer', 55), ('Shah',  5)],
      dtype=[('Name', '<U10'), ('Age', 'i1')])

In [12]:
struc_arr[0]

('Aayush', 12)

In [13]:
struc_arr[-1]

('Shah', 5)

In [14]:
struc_arr[0:2]

array([('Aayush', 12), ('Sameer', 55)],
      dtype=[('Name', '<U10'), ('Age', 'i1')])

In [16]:
#THIS TOO!
struc_arr['Name']

array(['Aayush', 'Sameer', 'Shah'], dtype='<U10')

In [17]:
#THIS TOO!
struc_arr['Age']

array([12, 55,  5], dtype=int8)

In [19]:
struc_arr.dtype

dtype([('Name', '<U10'), ('Age', 'i1')])

In [24]:
struc_arr.dtype.names

('Name', 'Age')

# 

### More.. flex... i... ble... dtypes 

In [25]:
dtype = [("X", np.float, 3), ("Y", np.int)]

In [27]:
aa = np.zeros(4, dtype= dtype)
aa

array([([0., 0., 0.], 0), ([0., 0., 0.], 0), ([0., 0., 0.], 0),
       ([0., 0., 0.], 0)], dtype=[('X', '<f8', (3,)), ('Y', '<i4')])

In [28]:
aa["X"]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 

### Remember DataFrame's Hierarchical / MultiIndex? 

In [31]:
dtype = [('gender', [('male', np.bool), ('female', np.bool)]), 
         ('location', np.float)]

In [32]:
np.zeros(5, dtype= dtype)

array([((False, False), 0.), ((False, False), 0.), ((False, False), 0.),
       ((False, False), 0.), ((False, False), 0.)],
      dtype=[('gender', [('male', '?'), ('female', '?')]), ('location', '<f8')])

In [42]:
# A better - real example
data = np.array([((True, False), 123.4),
          ((False, True), 1243.4),
          ((True, False), 1223.4)], dtype= dtype)

data

array([(( True, False),  123.4), ((False,  True), 1243.4),
       (( True, False), 1223.4)],
      dtype=[('gender', [('male', '?'), ('female', '?')]), ('location', '<f8')])

In [43]:
data['gender']

array([( True, False), (False,  True), ( True, False)],
      dtype=[('male', '?'), ('female', '?')])

In [47]:
data['gender']['male']

array([ True, False,  True])

Yeah! Like multiindex.

# 

# Next up
We will talk about sorting in numpy

# 